[package]
name = "cis_profile"
version = "0.1.0"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/fiji-flo/cis_profile-rust"
documentation = "https://docs.rs/crate/cis_profile"
keywords = ["profiles", "mozilla", "IAM"]
categories = []
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "data/", "README.md", "LICENSE"]

[features]
graphql = ["juniper"]
aws = ["rusoto_core", "rusoto_ssm"]
well_known = ["reqwest"]
vendored = ["openssl/vendored"]

[dependencies]
biscuit = "0.2.0"
ring = "0.14"
openssl = "0.10"
num-bigint = "0.2"
untrusted = "0.6"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = { version = "1.0.32", features = ["preserve_order"] }
chrono = "0.4"
chrono-tz = "0.5"

juniper = { version = "0.11.1", optional = true }
rusoto_core = { version = "0.36.0", optional = true }
rusoto_ssm = { version = "0.36.0", optional = true }
reqwest = { version = "0.9", optional = true }